### PR TITLE
Organize ROS related files

### PR DESCRIPTION
**Pull request by whikwon**

### CODE REVIEW

**Comment by mch5048** [comment]
`add_message_files( DIRECTORY msg
FILES
GoalObs.msg
)
`
Please comment these lines in the CMakelists.txt.
Other changes are valid.

**Review by kdh0429 — COMMENTED** [review]
I'm not sure whether 'cv_bridge' in CMakeList.txt (line 40) is needed in our project.

**Comment by mch5048** [comment]
@kdh0429  We will use OpenCV's functionality for target object detection when testing on the real robot environment. As far as I know, we must use openCV module provided by ros-kinetic for ros project, which requires cv_bridge for building package.

**Comment by whikwon** [comment]
@kdh0429 @mch5048 If possible, I want to remove all the packages not used for this project 1. Please review the PR from this point of view.

**Comment by whikwon** [comment]
Reflected the reviews @mch5048 @kdh0429

**Review by kdh0429 — APPROVED** [review]
It contains what we need for this project.

**Review by mch5048 — APPROVED** [review]
All seems good.

**Pull request merged**
