### PR TITLE
Add Controller for demo collection

### PR DESCRIPTION
**Pull request by kdh0429**
Components description
- open_manipulator_joint_space_publisher.py : publish joint space command 
- open_manipulator_goal_publisher.py : publish operation space command
- open_manipulator_position_control.py : solve inverse kinematics of given operation space command
- open_manipulator_demo_logger.py : log demo data in json format
- pos_read_write.py : control dynamixel

### CODE REVIEW

**Comment by whikwon** [comment]
Need to apply `isort` and `black`. You can easily apply them by executing `make dev` and `make format`

**Comment by whikwon** [comment]
I think `Makefile` has updated by @MrSyee and you need to rebase it
```
git checkout master
git pull origin master
git checkout feat/demo_controller
git rebase master
>> conflict will happen
>> resolve conflict by making Makefile same as master
git add Makefile
git rebase --continue  # rebase finished to master
make dev 
make format
# if all test has passed, 
git push origin feat/demo_controller 
```

**Comment by mch5048** [comment]
The functionality of the controller itself seems flawless except for the formatting issues suggested by @whikwon .

**Comment by kdh0429** [comment]
I'll reflect the comments as soon as possible.

**Comment by whikwon** [comment]
@kdh0429 After resolving conflict issue, could you share the commands so that I can follow to test the code? (maybe in gazebo?)

**Comment by kdh0429** [comment]
I have some problems with git commit.  I'v solved conflict issue and ran 'make dev' and 'make format'.  Then I added files with 'git add .' and tried to commit. When I try to commit I get errors about rospy like

ImportError while importing test module '/home/kim/kair_algorithms_draft/kair_algorithms_draft/scripts/test_om.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python2.7/dist-packages/six.py:699: in exec_
    exec("""exec _code_ in _globs_, _locs_""")
scripts/test_om.py:6: in <module>
    import rospy
E   ImportError: No module named rospy


Currently, my python path is 'export PYTHONPATH=$PYTHONPATH:/opt/ros/kinetic/lib/python2.7/dist-packages'. Can someone help me please? TT

**Comment by kdh0429** [comment]
However, when I run 'python' then 'import rospy' in terminal, it works well.

**Comment by whikwon** [comment]
@kdh0429 You need to add `rospy` in `scripts/requirements.txt` so that travis will know which packages should be installed. (remote)

Python2.7 execution for testing and just running seems to be different. (local)

And, If your branch has scripts that do not included both in master and your branch, please remove and push or make new branch from master (or rebase) and add your files.

**Comment by whikwon** [comment]
check `which python`

**Comment by kdh0429** [comment]
It says /usr/bin/python.

**Pull request closed without merging**
