### PR TITLE
Convert code to python 2.7

### PR DESCRIPTION
**Pull request by MrSyee**
Finished : flake8, pytest, black

issue : Recreate demo pickle file

### CODE REVIEW

**Comment by Curt-Park** [comment]
Please change TravisCI settings

**Comment by whikwon** [comment]
I changed Reacher env version v2 to v1

**Comment by whikwon** [comment]
Merge conflict occurred because of newly added reacher-v2 training scripts @MrSyee Please check.

**Review by whikwon — APPROVED** [review]
Good job

**Pull request merged**
